function Hv = hess_mult( Hinfo, v )

Hv = [Hinfo.diag_upper*v(:,1:end-1), zeros(size(v,1),1)] ...
   + [zeros(size(v,1),1), Hinfo.diag_lower*v(:,2:end)] ...
   + Hinfo.diag_left*(Hinfo.diag_center.*(Hinfo.diag_right*v)) ...
   + [Hinfo.off_diag*v(:,2:end), zeros(size(v,1),1)] ...
   + [zeros(size(v,1),1), Hinfo.off_diag'*v(:,1:end-1)];