function Hv = hess_mult( Hinfo, v )

Hv = zeros(size(v));
for i = 1:size(v,2)
    w = reshape(v(:,i),size(Hinfo.diag_left,1),size(Hinfo.diag_center,2));
    Hw = [Hinfo.diag_corner*w(:,1), zeros(size(w,1),size(w,2)-1)] + ...
        + [Hinfo.diag_upper*w(:,1:end-1), zeros(size(w,1),1)] ...
        + [zeros(size(w,1),1), Hinfo.diag_lower*w(:,2:end)] ...
        + Hinfo.diag_left*(Hinfo.diag_center.*(Hinfo.diag_right*w)) ...
        + [Hinfo.off_diag*w(:,2:end), zeros(size(w,1),1)] ...
        + [zeros(size(w,1),1), Hinfo.off_diag'*w(:,1:end-1)];
    Hv(:,i) = Hw(:);
end